DROP TABLE TRAIN;
DROP TABLE MODEL;
DROP TABLE MODELTEMPLATE;
DROP TABLE FILTER;
DROP TABLE DATADICDATA;
DROP TABLE DATADIC;
DROP TABLE DATA;
DROP TABLE DATASET;
DROP TABLE MESSAGE;
DROP TABLE USERCONTRIBUTION; 
DROP TABLE PROJECT;
DROP TABLE IMAGE;
DROP TABLE TOKEN;
DROP TABLE USER;

CREATE TABLE USER (
USERID VARCHAR(32) PRIMARY KEY,
PASSWORD VARCHAR(32) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
REGISTTIME DATETIME NOT NULL,
LASTLOGINTIME DATETIME NOT NULL,
STATUS CHAR(1) NOT NULL,
SUPPORTMONEY DOUBLE(7,2) NOT NULL DEFAULT '0',
REMAINMONEY DOUBLE(7,2) NOT NULL DEFAULT '0',
REMAINPIXEL INT NOT NULL DEFAULT '0'
) CHARSET=utf8;

CREATE TABLE TOKEN (
TOKEN VARCHAR(17) PRIMARY KEY,
USERID VARCHAR(32) NOT NULL,
EXPIRETIME DATETIME NOT NULL,
FOREIGN KEY(USERID) REFERENCES USER(USERID) ON DELETE CASCADE
) CHARSET=utf8;

CREATE TABLE IMAGE (
IMAGETYPE VARCHAR(2),
XAXIS INT,
YAXIS INT,
COLOR VARCHAR(7),
USERID VARCHAR(32) NOT NULL,
STATUS VARCHAR(1),
CREATETIME DATETIME NOT NULL,
PRIMARY KEY(IMAGETYPE, XAXIS, YAXIS),
FOREIGN KEY(USERID) REFERENCES USER(USERID) ON DELETE CASCADE
) CHARSET=utf8;

CREATE TABLE PROJECT (
PROJECTID VARCHAR(32) PRIMARY KEY NOT NULL,
PROJECTNAME VARCHAR(64) NOT NULL,
DESCRIPTION VARCHAR(256) NOT NULL,
COSTMONEY DOUBLE(7,2) NOT NULL,
SUPPORTEDMONEY DOUBLE(7,2) NOT NULL DEFAULT '0',
RELEASETIME DATETIME NOT NULL,
STARTTIME DATETIME,
STATUS CHAR(1) NOT NULL DEFAULT 1
)CHARSET=utf8;

CREATE TABLE USERCONTRIBUTION (
USERID VARCHAR(32) NOT NULL,
PROJECTID VARCHAR(32) NOT NULL,
CONTRIBUTETIME DATETIME NOT NULL,
CONTRIBUTEMONEY DOUBLE(7,2) NOT NULL,
REPAYITEMID CHAR(1),
REPAYITEMNUMBER INT, 
FOREIGN KEY(USERID) REFERENCES USER(USERID) ON DELETE CASCADE,
FOREIGN KEY(PROJECTID) REFERENCES PROJECT(PROJECTID) ON DELETE CASCADE
)CHARSET=utf8;

CREATE TABLE MESSAGE (
MESSAGEID VARCHAR(32) PRIMARY KEY,
FROMUSERID VARCHAR(32) NOT NULL,
TOUSERID VARCHAR(32) NOT NULL,
MESSAGE VARCHAR(1024) NOT NULL,
ISREAD BOOL NOT NULL,
CREATETIME DATETIME NOT NULL,
FOREIGN KEY(FROMUSERID) REFERENCES USER(USERID) ON DELETE CASCADE,
FOREIGN KEY(TOUSERID) REFERENCES USER(USERID) ON DELETE CASCADE
) CHARSET=utf8;

CREATE TABLE DATASET (
DATASETID VARCHAR(24) PRIMARY KEY,
DATASETNAME VARCHAR(32) NOT NULL,
DESCRIPTION VARCHAR(1024),
USERID VARCHAR(32) NOT NULL,
TYPE VARCHAR(8) NOT NULL,
FORMAT VARCHAR(8) NOT NULL,
KEYWORDS VARCHAR(128),
TITLES VARCHAR(1024),
SHAREPOLICY CHAR(1) NOT NULL,
CREATETIME DATETIME NOT NULL,
UNIQUE INDEX DATASET_INDEX1 (USERID, DATASETNAME),
FOREIGN KEY(USERID) REFERENCES USER(USERID) ON DELETE CASCADE
) CHARSET=utf8;

CREATE TABLE DATA (
DATAID VARCHAR(32) PRIMARY KEY,
DATASETID VARCHAR(24) NOT NULL,
IDX INT NOT NULL,
REF VARCHAR(1024),
X TEXT,
Y TEXT,
FOREIGN KEY(DATASETID) REFERENCES DATASET(DATASETID) ON DELETE CASCADE
) CHARSET=utf8;

CREATE TABLE DATADIC (
DATADICID VARCHAR(24) PRIMARY KEY,
DATADICNAME VARCHAR(32) NOT NULL,
DESCRIPTION VARCHAR(1024),
USERID VARCHAR(32) NOT NULL,
SHAREPOLICY CHAR(1) NOT NULL,
UNIQUE INDEX DATADIC_INDEX1 (USERID, DATADICNAME),
FOREIGN KEY(USERID) REFERENCES USER(USERID)
) CHARSET=utf8;

CREATE TABLE DATADICDATA (
DATADICID VARCHAR(24) NOT NULL,
KII INT NOT NULL,
VALUE VARCHAR(256) NOT NULL,
FOREIGN KEY(DATADICID) REFERENCES DATADIC(DATADICID) ON DELETE CASCADE
) CHARSET=utf8;

CREATE TABLE FILTER (
FILTERNAME VARCHAR(32) PRIMARY KEY
) CHARSET=utf8;

CREATE TABLE MODELTEMPLATE (
MODELTEMPLATEID VARCHAR(17) PRIMARY KEY,
MODELTEMPLATENAME VARCHAR(32) NOT NULL,
USERID VARCHAR(32) NOT NULL,
ALGORITHM VARCHAR(16) NOT NULL,
SCRIPT VARCHAR(1024) NOT NULL,
DATASETID VARCHAR(24) NOT NULL,
XCOLUMN VARCHAR(32) NOT NULL,
XFILTER VARCHAR(1024) NOT NULL,
YCOLUMN VARCHAR(32) NOT NULL,
YFILTER VARCHAR(1024) NOT NULL,
SHAREPOLICY CHAR(1) NOT NULL,
CREATETIME DATETIME NOT NULL,
UNIQUE INDEX MODELTEMPLATE_INDEX1 (USERID, MODELTEMPLATENAME),
FOREIGN KEY(USERID) REFERENCES USER(USERID) ON DELETE CASCADE
) CHARSET=utf8;

CREATE TABLE MODEL (
MODELID VARCHAR(31) PRIMARY KEY,
MODELTEMPLATEID VARCHAR(17) NOT NULL,
USERID VARCHAR(32) NOT NULL,
STATUS CHAR(1) NOT NULL,
PARENTMODELID VARCHAR(31),
STRUCTURE LONGBLOB,
CREATETIME DATETIME NOT NULL,
UPDATETIME DATETIME NOT NULL,
FOREIGN KEY(USERID) REFERENCES USER(USERID) ON DELETE CASCADE,
FOREIGN KEY(MODELTEMPLATEID) REFERENCES MODELTEMPLATE(MODELTEMPLATEID) ON DELETE CASCADE
) CHARSET=utf8;

CREATE TABLE TRAIN (
TRAINID VARCHAR(32) PRIMARY KEY,
MODELID VARCHAR(31) NOT NULL,
EPOCHDATACNT INT NOT NULL,
EPOCHCNT INT,
STARTTIME DATETIME NOT NULL,
ENDTIME DATETIME,
TOTALSECOND INT,
FOREIGN KEY(MODELID) REFERENCES MODEL(MODELID) ON DELETE CASCADE
) CHARSET=utf8;

